### ISSUE TITLE
Null when `getMethodInvocationsLocal()`

### ISSUE THREAD

**Issue by mauricioaniche** [mauricioaniche/ck#65]
See class https://github.com/mauricioaniche/ck/blob/master/fixtures/real-world/ByteBufferAsyncWritableChannel.java. It contains a subclass `ChunkData`. If we call `getMethodInvocationsLocal()` to the `ChunkData/2` constructor, it returns null. 

I believe that's a bug.

**Comment by jan-gerling** [comment]
I will have a look at it. You can assign the issue to me.

**Comment by jan-gerling** [comment]
I was able to reproduce this error and will work on a fix.

**Comment by jan-gerling** [comment]
**Problem:**
For classes with no visible methods, the local method invocations were not set, because I called it to generate [TCC and LCC](https://github.com/mauricioaniche/ck/blob/12731b1fed7738e52401ee067efef1de3f2a5cc9/src/main/java/com/github/mauricioaniche/ck/metric/TightClassCohesion.java#L115-L131) where these cases can be skipped.

**Solution:**
Generate empty HashSets for all cases.
